apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kite-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kite-service.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.service.port | quote }}
  METRICS_PORT: {{ .Values.service.metricsPort | quote }}
  APP_VERSION: {{ .Values.image.tag | default .Chart.AppVersion | quote }}
  {{- with .Values.config }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
