image:
  repository: "kite-service"
  tag: "0.0.1"
  pullPolicy: Never

replicaCount: 2

ingress:
  enabled: true
  hosts:
    - host: kite-staging.example.com
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

serviceMonitor:
  enabled: true
  additionalLabels:
    release: kube-prometheus-stack
